export const Java = [
    {
      question: "What is Java?",
      option1: "A web browser",
      option2: "A programming language",
      option3: "An operating system",
      option4: "A text editor",
      ans: 2,
    },
    {
      question: "Which keyword is used to define a class in Java?",
      option1: "class",
      option2: "define",
      option3: "create",
      option4: "new",
      ans: 1,
    },
    {
      question: "How do you create an object in Java?",
      option1: "Object obj = new Object();",
      option2: "Object obj = Object();",
      option3: "Object obj = create Object();",
      option4: "Object obj = new();",
      ans: 1,
    },
    {
      question: "What is inheritance in Java?",
      option1: "A way to create new classes from existing classes",
      option2: "A way to package classes",
      option3: "A way to handle exceptions",
      option4: "A way to import libraries",
      ans: 1,
    },
    {
      question: "Which method is used to start a thread in Java?",
      option1: "run()",
      option2: "start()",
      option3: "execute()",
      option4: "begin()",
      ans: 2,
    },
    {
      question: "How do you handle exceptions in Java?",
      option1: "Using try/catch",
      option2: "Using if/else",
      option3: "Using switch/case",
      option4: "Using for/while",
      ans: 1,
    },
    {
      question: "What is polymorphism in Java?",
      option1: "The ability to define multiple methods with the same name",
      option2: "The ability to inherit from multiple classes",
      option3: "The ability to define classes within classes",
      option4: "The ability to import multiple libraries",
      ans: 1,
    },
    {
      question: "Which of the following is a valid Java main method signature?",
      option1: "public static void main(String[] args)",
      option2: "public void main(String args)",
      option3: "public static int main(String[] args)",
      option4: "void main(String[] args)",
      ans: 1,
    },
    {
      question: "What is encapsulation in Java?",
      option1: "The wrapping of data and methods into a single unit",
      option2: "The ability to inherit methods from a parent class",
      option3: "The ability to create multiple instances of a class",
      option4: "The process of converting data types",
      ans: 1,
    },
    {
      question: "Which keyword is used to inherit a class in Java?",
      option1: "inherits",
      option2: "extends",
      option3: "implements",
      option4: "inherits",
      ans: 2,
    },
  ];
  