export const Python = [
    {
      question: "What is Python?",
      option1: "A web browser",
      option2: "A programming language",
      option3: "A database management system",
      option4: "A text editor",
      ans: 2,
    },
    {
      question: "How do you create a list in Python?",
      option1: "list = ()",
      option2: "list = {}",
      option3: "list = []",
      option4: "list = <>",
      ans: 3,
    },
    {
      question: "Which keyword is used to define a function in Python?",
      option1: "function",
      option2: "def",
      option3: "func",
      option4: "lambda",
      ans: 2,
    },
    {
      question: "How do you handle exceptions in Python?",
      option1: "using try/except",
      option2: "using if/else",
      option3: "using while/except",
      option4: "using for/try",
      ans: 1,
    },
    {
      question: "Which data type is used to store multiple items in a single variable in Python?",
      option1: "String",
      option2: "Integer",
      option3: "List",
      option4: "Boolean",
      ans: 3,
    },
    {
      question: "What does the 'len()' function do in Python?",
      option1: "Calculates the length of an object",
      option2: "Converts data types",
      option3: "Sorts a list",
      option4: "Finds the maximum value in a list",
      ans: 1,
    },
    {
      question: "How do you start a block of code in Python?",
      option1: "Using curly braces {}",
      option2: "Using square brackets []",
      option3: "Using indentation",
      option4: "Using parentheses ()",
      ans: 3,
    },
    {
      question: "Which module in Python is used to work with dates and times?",
      option1: "datetime",
      option2: "time",
      option3: "calendar",
      option4: "dateutil",
      ans: 1,
    },
    {
      question: "What is a dictionary in Python?",
      option1: "An ordered collection of items",
      option2: "An unordered collection of items",
      option3: "A collection of key-value pairs",
      option4: "A collection of unique items",
      ans: 3,
    },
    {
      question: "What is a lambda function in Python?",
      option1: "A named function",
      option2: "An anonymous function",
      option3: "A function defined using def keyword",
      option4: "A recursive function",
      ans: 2,
    },
  ];
  